<a href="https://colab.research.google.com/github/anushavk416/Datascience-Tasks/blob/main/numpyTasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# Part 1: Creating and Reshaping Arrays


In [13]:
# Creating arrays
# 1D array of 10 equally spaced values between 0 and 50
arr1 = np.linspace(0, 50, 10)
print("1D Array:")
print(arr1)

# 2D array (3x3) random integers between 5 and 20
arr2 = np.random.randint(5, 21, (3,3))
print("2D Array:")
print(arr2)

1D Array:
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
2D Array:
[[ 8 13 12]
 [15 14 15]
 [13 20  8]]


In [14]:
# 2. Array Dimensions
print("Dimensions of arr1:", arr1.ndim)
print("Dimensions of arr2:", arr2.ndim)

print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

Dimensions of arr1: 1
Dimensions of arr2: 2
Shape of arr1: (10,)
Shape of arr2: (3, 3)


In [15]:
# 3. Reshaping
reshaped = arr1.reshape(2,5)
print("Reshaped Array (2x5):")
print(reshaped)

flattened = reshaped.flatten()
print("Flattened back to 1D:")
print(flattened)

Reshaped Array (2x5):
[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
Flattened back to 1D:
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


# Part 2: Indexing and Slicing

In [16]:
# 4. Indexing
# element at 2nd row, 3rd column
print("Element at 2nd row, 3rd column:")
print(arr2[1,2])

# first two rows and last two columns
print("First two rows and last two columns:")
print(arr2[:2, -2:])

Element at 2nd row, 3rd column:
15
First two rows and last two columns:
[[13 12]
 [14 15]]


In [17]:
# 5. Slicing

# first four elements from flattened array
print("First four elements:")
print(flattened[:4])

# reverse the 1D array
print("Reversed 1D array:")
print(arr1[::-1])

First four elements:
[ 0.          5.55555556 11.11111111 16.66666667]
Reversed 1D array:
[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


# Part 3: Array Operations


In [18]:
# 6. Create another 1D array
arr3 = np.random.randint(1,11,10)
print("New Array (1 to 10 integers):")
print(arr3)

# Addition
print("Addition:")
print(arr1 + arr3)

# Multiplication
print("Multiplication:")
print(arr1 * arr3)

# Subtract constant
print("Subtract 5:")
print(arr1 - 5)

New Array (1 to 10 integers):
[ 9  3  3  7  3 10 10  5  7  6]
Addition:
[ 9.          8.55555556 14.11111111 23.66666667 25.22222222 37.77777778
 43.33333333 43.88888889 51.44444444 56.        ]
Multiplication:
[  0.          16.66666667  33.33333333 116.66666667  66.66666667
 277.77777778 333.33333333 194.44444444 311.11111111 300.        ]
Subtract 5:
[-5.          0.55555556  6.11111111 11.66666667 17.22222222 22.77777778
 28.33333333 33.88888889 39.44444444 45.        ]


# Part 4: Random Number Generation

In [19]:
# random values between 0 and 1
rand1 = np.random.rand(5)
print("Random values (0 to 1):")
print(rand1)

# random values between -1 and 1
rand2 = np.random.uniform(-1,1,5)
print("Random values (-1 to 1):")
print(rand2)

Random values (0 to 1):
[0.77468197 0.46443802 0.26653243 0.04148458 0.35241582]
Random values (-1 to 1):
[-0.09968544 -0.77811458  0.36742023 -0.37392221  0.75402014]


# Part 5: Bonus

In [20]:
n = int(input("Enter a number n: "))

matrix = np.random.randint(1,101,(n,n))

print("Generated Matrix:")
print(matrix)

print("Sum of all elements:")
print(np.sum(matrix))

Enter a number n: 3
Generated Matrix:
[[43 34 37]
 [95 94 64]
 [42 33 80]]
Sum of all elements:
522
